### ISSUE TITLE
`flatten_timepoint_specific_output_overrides` does not update visualization table

### ISSUE THREAD

**Issue by dweindl** [PEtab-dev/libpetab-python#313]
`flatten_timepoint_specific_output_overrides` does not update the visualization table. The resulting problem does not pass validation. Can be observed, for example, with https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/tree/v2024.10.15/Benchmark-Models/Isensee_JCB2018.

**Comment by m-philipps** [comment]
A flattened visualization table is probably not useful so the table could be removed for the flattened problem, as long as the visualization table stays optional.

**Comment by dweindl** [comment]
Agreed, unsetting `problem.visualization_df` would suffice.

**Comment by m-philipps** [comment]
fixed in #316
