### ISSUE TITLE
Unreachable TypeError in `petab.parameter_mapping.apply_overrides_for_observable`

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/libpetab-python#59]
I don't think https://github.com/PEtab-dev/libpetab-python/blob/0917194199df10b40e3c16dd567a1fdcda0c08c7/petab/parameter_mapping.py#L365 can ever be reached.

If `overridee_id` is not present in `mapping`, the code will simply add a new entry and not throw a `KeyError`.

**Comment by yannikschaelte** [comment]
that seems correct, as mapping is just a dict. it should likely check for existence of that key instead.

**Comment by dweindl** [comment]
Apparently my fault... not sure what I was thinking back then...
