### ISSUE TITLE
pandas 1.2.x requirement?

### ISSUE THREAD

**Issue by fbergmann** [PEtab-dev/libpetab-python#75]
I just tried installing petab in the colab environment, unfortunately that failed, since colab only seems to work with pandas up to 1.1.5. Any chance we could lower our requirement here?

```
Collecting petab
  Downloading petab-0.1.20-py3-none-any.whl (84 kB)
...
Collecting pandas>=1.2.0
  Downloading pandas-1.3.3-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
     |████████████████████████████████| 11.3 MB 12.6 MB/s 
...
Installing collected packages: pandas, colorama, petab
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.3 which is incompatible.
Successfully installed colorama-0.4.4 pandas-1.3.3 petab-0.1.20
WARNING: The following packages were previously imported in this runtime:
  [pandas]
You must restart the runtime in order to use newly installed versions.
```

**Comment by fbergmann** [comment]
This came in with commit: 1f6495f819079cb134e4a81d34dc7afb808b0eb9, so it seems to be required for now, i'll just try an older version

**Comment by dweindl** [comment]
I'd prefer collab supporting a more recent pandas version :)

Did you try using petab after that message above? I just gave it a quick try. Despite that message, pandas was upgraded and petab got installed and was working. However, I am not sure if this breaks anything else in collab...

**Comment by fbergmann** [comment]
Guess nothing can be done, petab is actually working after installation, its the colab convenience features like uploading / downloading that failed for me. But there are workarounds for that. so i guess this can be closed.
